language: node_js
node_js:
  - 10

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - npm install -g npm@6.9.0

script:
  - npm run test:client

cache:
  npm: false
