language: node_js
node_js:
  - 10

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm install -g npm@6.9.0

script:
  - npm run test:client

cache:
  npm: false

addons:
  chrome: stable
