language: node_js
node_js:
  - 10

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - npm install -g npm@6.9.0

script:
  - npm run test:client

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

cache:
  npm: false
