language: node_js
node_js:
  - 10
services:
  - xvfb
addons:
  chrome: stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - npm install -g npm@6.9.0

script:
  - npm run build:client
  - npm run test:client

before_script:
  - export DISPLAY=:99.0

cache:
  npm: false
